[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn web.app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 2"
healthcheckPath = "/status"